name: flutter_news_app
description: A new Flutter application.

publish_to: "none" # Prevents accidental publishing

environment:
  sdk: ">=2.12.0 <4.0.0" # Updated for null safety compatibility

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Updated null-safe version of http
  provider: ^6.0.5 # Null-safe provider dependency
  cupertino_icons: ^1.0.5 # Null-safe version of cupertino_icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
